.TH "CLManager" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLManager \- The \fBCLManager\fP class Purpose: Interfaces the \fBCLGLTask\fP and \fBCLTask\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clmanager\&.h>\fP
.PP
Inherits \fBCLGLTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLManager\fP ()"
.br
.RI "\fI\fBCLManager\fP class constructure\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBCLManager\fP class Purpose: Interfaces the \fBCLGLTask\fP and \fBCLTask\fP class\&. 
.PP
Definition at line 10 of file clmanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
