.TH "FrameRate" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameRate \- The \fBFrameRate\fP class provides the functulities for calculating the rendering frame rate The class calculate the rendering rate in FPS and returns the rendering rate through GetRate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <framerate\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameRate\fP ()"
.br
.RI "\fI\fBFrameRate\fP class constructor\&. \fP"
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.RI "\fICalculate calculates the frame rate\&. \fP"
.ti -1c
.RI "int \fBGetRate\fP ()"
.br
.RI "\fIGetRate gets the current frame rate\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBFrameRate\fP class provides the functulities for calculating the rendering frame rate The class calculate the rendering rate in FPS and returns the rendering rate through GetRate\&. 
.PP
Definition at line 11 of file framerate\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int FrameRate::GetRate ()\fC [inline]\fP"

.PP
GetRate gets the current frame rate\&. 
.PP
\fBReturns:\fP
.RS 4
the frame rate value 
.RE
.PP

.PP
Definition at line 28 of file framerate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
