.TH "GROManager" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GROManager \- The \fBGROManager\fP class handles the GRO file data we deal with the gro file data as a a text line by line So the data will be stored in QStringList object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gromanager\&.h>\fP
.PP
Inherits \fBMemoryManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGROManager\fP ()"
.br
.RI "\fI\fBGROManager\fP class constructor\&. \fP"
.ti -1c
.RI "void \fBFetchData\fP ()"
.br
.RI "\fIFetchData fetches gro file data\&. \fP"
.ti -1c
.RI "void \fBFetchStructure\fP ()"
.br
.RI "\fIFetchStructure fetches the molecules structure\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBGROManager\fP class handles the GRO file data we deal with the gro file data as a a text line by line So the data will be stored in QStringList object\&. 
.PP
Definition at line 12 of file gromanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
