.TH "MemoryManager" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryManager \- The \fBMemoryManager\fP inherits the \fBDataStructure\fP and provide access to the \fBDataStructure\fP function\&. It is inherited as a public vartual class by different class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memorymanager\&.h>\fP
.PP
Inherits \fBDataStructure\fP\&.
.PP
Inherited by \fBGROManager\fP\fC [virtual]\fP, \fBMMF\fP\fC [virtual]\fP, \fBSTL\fP\fC [virtual]\fP, and \fBXTCManager\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryManager\fP ()"
.br
.RI "\fI\fBMemoryManager\fP class constructure\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBMemoryManager\fP inherits the \fBDataStructure\fP and provide access to the \fBDataStructure\fP function\&. It is inherited as a public vartual class by different class\&. 
.PP
Definition at line 10 of file memorymanager\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
