.TH "SphereShader" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SphereShader \- The \fBSphereShader\fP class interfaces the QOpenGL shader progrsm class The class provides two main functions: 1)Create and 2)GetShader\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sphereshader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSphereShader\fP ()"
.br
.RI "\fI\fBSphereShader\fP class constructor\&. \fP"
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.RI "\fICreate creates the QOpenGL shader program\&. \fP"
.ti -1c
.RI "QOpenGLShaderProgram * \fBGetShader\fP ()"
.br
.RI "\fIGetShader getter for the QOpenGL shader program\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBSphereShader\fP class interfaces the QOpenGL shader progrsm class The class provides two main functions: 1)Create and 2)GetShader\&. 
.PP
Definition at line 11 of file sphereshader\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QOpenGLShaderProgram* SphereShader::GetShader ()\fC [inline]\fP"

.PP
GetShader getter for the QOpenGL shader program\&. 
.PP
\fBReturns:\fP
.RS 4
the QOpenGL shader program 
.RE
.PP

.PP
Definition at line 29 of file sphereshader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
