.TH "SphereVAO" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SphereVAO \- The \fBSphereVAO\fP class interfaces the QOpenGL vertex array object class The class provides three main functions: 1)Create, 2)Bind, and 3) Release\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spherevao\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSphereVAO\fP ()"
.br
.RI "\fI\fBSphereVAO\fP class constructor\&. \fP"
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.RI "\fICreate creates the QOpenGL vertex array object\&. \fP"
.ti -1c
.RI "void \fBBind\fP ()"
.br
.RI "\fIBind binds the QOpenGL vertex array object\&. \fP"
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.RI "\fIRelease releases the QOpenGL vertex array object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBSphereVAO\fP class interfaces the QOpenGL vertex array object class The class provides three main functions: 1)Create, 2)Bind, and 3) Release\&. 
.PP
Definition at line 10 of file spherevao\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
