.TH "STRUCT_GPULipidParticle" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STRUCT_GPULipidParticle \- GPULipidParticle contains the structure of the lipid particles\&. We manage this structure through the \fBDataStructure\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structure\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBLipidID\fP"
.br
.ti -1c
.RI "unsigned int \fBParticleID\fP"
.br
.ti -1c
.RI "float \fBPosition\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPULipidParticle contains the structure of the lipid particles\&. We manage this structure through the \fBDataStructure\fP class\&. 

the GPULipidParticle has three members: 1)lipid ID, 2)particle ID, and 3)the particle position 
.PP
Definition at line 164 of file structure\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int STRUCT_GPULipidParticle::ParticleID"
LipidID contains the lipid ID 
.PP
Definition at line 167 of file structure\&.h\&.
.SS "float STRUCT_GPULipidParticle::Position[3]"
ParticleID contains the particle ID 
.PP
Definition at line 168 of file structure\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
