.TH "STRUCT_GPULipidSpace" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STRUCT_GPULipidSpace \- GPULipidSpace contains the structure of the lipid space\&. We manage this structure through the \fBDataStructure\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structure\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBLipidID\fP"
.br
.ti -1c
.RI "float \fBLipidCOM\fP [3]"
.br
.ti -1c
.RI "float \fBRadius\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPULipidSpace contains the structure of the lipid space\&. We manage this structure through the \fBDataStructure\fP class\&. 

the GPULipidSpace has three members: 1)lipid id, 2)center of the mass of the lipid, and 3)lipid spca radius 
.PP
Definition at line 150 of file structure\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float STRUCT_GPULipidSpace::LipidCOM[3]"
LipidID contains the lipid ID 
.PP
Definition at line 153 of file structure\&.h\&.
.SS "float STRUCT_GPULipidSpace::Radius"
LipidCOM contains the center of mass of the lipid 
.PP
Definition at line 154 of file structure\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
