.TH "STRUCT_VetexColor" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STRUCT_VetexColor \- VertexColor contains the structure of vertex color\&. We manage this structure through the \fBDataStructure\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structure\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBR\fP"
.br
.ti -1c
.RI "float \fBG\fP"
.br
.ti -1c
.RI "float \fBB\fP"
.br
.ti -1c
.RI "float \fBA\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VertexColor contains the structure of vertex color\&. We manage this structure through the \fBDataStructure\fP class\&. 

the VertexColor has four members: 1)R, 2)G, 3)B and 4)A 
.PP
Definition at line 178 of file structure\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float STRUCT_VetexColor::A"
B contains the blue value 
.PP
Definition at line 183 of file structure\&.h\&.
.SS "float STRUCT_VetexColor::B"
G contains the green value 
.PP
Definition at line 182 of file structure\&.h\&.
.SS "float STRUCT_VetexColor::G"
R contains the red value 
.PP
Definition at line 181 of file structure\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
