.TH "STRUCT_GPUProteinParticle" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STRUCT_GPUProteinParticle \- GPUProteinParticle contains the structure of the protein particles\&. We manage this structure through the \fBDataStructure\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structure\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "short \fBProteinID\fP"
.br
.ti -1c
.RI "unsigned int \fBParticleID\fP"
.br
.ti -1c
.RI "float \fBPosition\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPUProteinParticle contains the structure of the protein particles\&. We manage this structure through the \fBDataStructure\fP class\&. 

the GPUProteinParticle has three members: 1)protein ID, 2)particle ID, and 3)the particle position 
.PP
Definition at line 136 of file structure\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int STRUCT_GPUProteinParticle::ParticleID"
ProteinID contains the protein ID 
.PP
Definition at line 139 of file structure\&.h\&.
.SS "float STRUCT_GPUProteinParticle::Position[3]"
ParticleID contains the particle ID 
.PP
Definition at line 140 of file structure\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
