.TH "XDR" 3 "Wed Jun 21 2017" "RealTimeMDSRendering" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XDR \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBxdr_ops\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "enum xdr_op \fBx_op\fP"
.br
.ti -1c
.RI "struct \fBXDR::xdr_ops\fP     * \fBx_ops\fP"
.br
.ti -1c
.RI "char * \fBx_private\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file xdrfile\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RealTimeMDSRendering from the source code\&.
